// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NZUCManagementSystemIA.Shared.Models
{
    [Table("AuthorizerTable")]
    public partial class AuthorizerTable
    {
        [Key]
        public int Id { get; set; }
        public int? AuthorizerNameId { get; set; }

        [ForeignKey("AuthorizerNameId")]
        [InverseProperty("AuthorizerTables")]
        public virtual EmployeeTable AuthorizerName { get; set; }
    }
}