// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NZUCManagementSystemIA.Shared.Models
{
    [Table("BudgetTypeTable")]
    public partial class BudgetTypeTable
    {
        public BudgetTypeTable()
        {
            IncomeExpenseBudgetTypes = new HashSet<IncomeExpenseBudgetType>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string BudgetType { get; set; }

        [InverseProperty("TypeofBudget")]
        public virtual ICollection<IncomeExpenseBudgetType> IncomeExpenseBudgetTypes { get; set; }
    }
}