// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NZUCManagementSystemIA.Shared.Models
{
    [Table("Departments Table")]
    public partial class Departments_Table
    {
        public Departments_Table()
        {
            EmployeeTables = new HashSet<EmployeeTable>();
            OperatingIncomeExpenses = new HashSet<OperatingIncomeExpense>();
            ReviewTransactionTables = new HashSet<ReviewTransactionTable>();
            TransactionTables = new HashSet<TransactionTable>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string DepartmentName { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string DepartmentCode { get; set; }

        [InverseProperty("Department")]
        public virtual ICollection<EmployeeTable> EmployeeTables { get; set; }
        [InverseProperty("Department")]
        public virtual ICollection<OperatingIncomeExpense> OperatingIncomeExpenses { get; set; }
        [InverseProperty("Department")]
        public virtual ICollection<ReviewTransactionTable> ReviewTransactionTables { get; set; }
        [InverseProperty("Department")]
        public virtual ICollection<TransactionTable> TransactionTables { get; set; }
    }
}