// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NZUCManagementSystemIA.Shared.Models
{
    [Table("EmployeeTable")]
    public partial class EmployeeTable
    {
        public EmployeeTable()
        {
            AuthorizerTables = new HashSet<AuthorizerTable>();
            ReviewTransactionTables = new HashSet<ReviewTransactionTable>();
            ReviewersTables = new HashSet<ReviewersTable>();
        }

        [Key]
        public int Id { get; set; }
        [Column(TypeName = "text")]
        public string EmployeeName { get; set; }
        public int? DepartmentId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string EmployeeID { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DateOfBirth { get; set; }
        [Column(TypeName = "text")]
        public string JobDescription { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string NRC { get; set; }
        public int? Salary { get; set; }
        public int? GenderId { get; set; }

        [ForeignKey("DepartmentId")]
        [InverseProperty("EmployeeTables")]
        public virtual Departments_Table Department { get; set; }
        [ForeignKey("GenderId")]
        [InverseProperty("EmployeeTables")]
        public virtual GenderTable Gender { get; set; }
        [ForeignKey("Salary")]
        [InverseProperty("EmployeeTables")]
        public virtual SalaryTable SalaryNavigation { get; set; }
        [InverseProperty("AuthorizerName")]
        public virtual ICollection<AuthorizerTable> AuthorizerTables { get; set; }
        [InverseProperty("Employee")]
        public virtual ICollection<ReviewTransactionTable> ReviewTransactionTables { get; set; }
        [InverseProperty("Employee")]
        public virtual ICollection<ReviewersTable> ReviewersTables { get; set; }
    }
}