// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NZUCManagementSystemIA.Shared.Models
{
    [Table("GenderTable")]
    public partial class GenderTable
    {
        public GenderTable()
        {
            EmployeeTables = new HashSet<EmployeeTable>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Gender { get; set; }

        [InverseProperty("Gender")]
        public virtual ICollection<EmployeeTable> EmployeeTables { get; set; }
    }
}