// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NZUCManagementSystemIA.Shared.Models
{
    public partial class IncomeExpensesOperatingType
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string IncomeExpenseType { get; set; }
        public int? OperatingType { get; set; }

        [ForeignKey("OperatingType")]
        [InverseProperty("IncomeExpensesOperatingTypes")]
        public virtual OperatingType OperatingTypeNavigation { get; set; }
    }
}