// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NZUCManagementSystemIA.Shared.Models
{
    public partial class OperatingType
    {
        public OperatingType()
        {
            IncomeExpensesOperatingTypes = new HashSet<IncomeExpensesOperatingType>();
            OperatingIncomeExpenses = new HashSet<OperatingIncomeExpense>();
        }

        [Key]
        public int Id { get; set; }
        [Column("OperatingType")]
        [StringLength(50)]
        [Unicode(false)]
        public string OperatingType1 { get; set; }

        [InverseProperty("OperatingTypeNavigation")]
        public virtual ICollection<IncomeExpensesOperatingType> IncomeExpensesOperatingTypes { get; set; }
        [InverseProperty("IncomeExpenseOperatingTypeNavigation")]
        public virtual ICollection<OperatingIncomeExpense> OperatingIncomeExpenses { get; set; }
    }
}