// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NZUCManagementSystemIA.Shared.Models
{
    public partial class OperatingIncomeExpense
    {
        [Key]
        public int Id { get; set; }
        public int? IncomeExpenseOperatingType { get; set; }
        public int? Amount { get; set; }
        public int? ReviewerId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DateMonth { get; set; }
        public int? ConferenceId { get; set; }
        public int? DepartmentId { get; set; }

        [ForeignKey("ConferenceId")]
        [InverseProperty("OperatingIncomeExpenses")]
        public virtual ConferencesAndField Conference { get; set; }
        [ForeignKey("DepartmentId")]
        [InverseProperty("OperatingIncomeExpenses")]
        public virtual Departments_Table Department { get; set; }
        [ForeignKey("IncomeExpenseOperatingType")]
        [InverseProperty("OperatingIncomeExpenses")]
        public virtual OperatingType IncomeExpenseOperatingTypeNavigation { get; set; }
        [ForeignKey("ReviewerId")]
        [InverseProperty("OperatingIncomeExpenses")]
        public virtual ReviewersTable Reviewer { get; set; }
    }
}