// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NZUCManagementSystemIA.Shared.Models
{
    public partial class PaymentType
    {
        public PaymentType()
        {
            ReviewTransactionTables = new HashSet<ReviewTransactionTable>();
        }

        [Key]
        public int Id { get; set; }
        [Column("PaymentType")]
        [StringLength(50)]
        [Unicode(false)]
        public string PaymentType1 { get; set; }

        [InverseProperty("PaymentType")]
        public virtual ICollection<ReviewTransactionTable> ReviewTransactionTables { get; set; }
    }
}