// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NZUCManagementSystemIA.Shared.Models
{
    [Table("PaymentMethodTable")]
    public partial class PaymentMethodTable
    {
        public PaymentMethodTable()
        {
            ReviewTransactionTables = new HashSet<ReviewTransactionTable>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string PaymentMethod { get; set; }

        [InverseProperty("PaymentMethod")]
        public virtual ICollection<ReviewTransactionTable> ReviewTransactionTables { get; set; }
    }
}