// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NZUCManagementSystemIA.Shared.Models
{
    [Table("ReviewTransactionTable")]
    public partial class ReviewTransactionTable
    {
        [Key]
        public int id { get; set; }
        public int? EmployeeId { get; set; }
        public int? DepartmentId { get; set; }
        public int? ReviewerId { get; set; }
        public int? Amount { get; set; }
        [Column(TypeName = "text")]
        public string Reason { get; set; }
        public int? PaymentMethodId { get; set; }
        public int? PaymentTypeId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Authorized { get; set; }
        public int? Status { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DateIssued { get; set; }

        [ForeignKey("DepartmentId")]
        [InverseProperty("ReviewTransactionTables")]
        public virtual Departments_Table Department { get; set; }
        [ForeignKey("EmployeeId")]
        [InverseProperty("ReviewTransactionTables")]
        public virtual EmployeeTable Employee { get; set; }
        [ForeignKey("PaymentMethodId")]
        [InverseProperty("ReviewTransactionTables")]
        public virtual PaymentMethodTable PaymentMethod { get; set; }
        [ForeignKey("PaymentTypeId")]
        [InverseProperty("ReviewTransactionTables")]
        public virtual PaymentType PaymentType { get; set; }
        [ForeignKey("ReviewerId")]
        [InverseProperty("ReviewTransactionTables")]
        public virtual ReviewersTable Reviewer { get; set; }
        [ForeignKey("Status")]
        [InverseProperty("ReviewTransactionTables")]
        public virtual TransactionStatus StatusNavigation { get; set; }
    }
}