// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NZUCManagementSystemIA.Shared.Models
{
    [Table("ReviewersTable")]
    public partial class ReviewersTable
    {
        public ReviewersTable()
        {
            OperatingIncomeExpenses = new HashSet<OperatingIncomeExpense>();
            ReviewTransactionTables = new HashSet<ReviewTransactionTable>();
            TransactionTables = new HashSet<TransactionTable>();
        }

        [Key]
        public int Id { get; set; }
        public int? EmployeeId { get; set; }

        [ForeignKey("EmployeeId")]
        [InverseProperty("ReviewersTables")]
        public virtual EmployeeTable Employee { get; set; }
        [InverseProperty("Reviewer")]
        public virtual ICollection<OperatingIncomeExpense> OperatingIncomeExpenses { get; set; }
        [InverseProperty("Reviewer")]
        public virtual ICollection<ReviewTransactionTable> ReviewTransactionTables { get; set; }
        [InverseProperty("Reviewer")]
        public virtual ICollection<TransactionTable> TransactionTables { get; set; }
    }
}