// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NZUCManagementSystemIA.Shared.Models
{
    [Table("TransactionTable")]
    public partial class TransactionTable
    {
        [Key]
        public int Id { get; set; }
        public int? DepartmentID { get; set; }
        public int? Amount { get; set; }
        public int? ReviewerId { get; set; }
        public int? EmployeeId { get; set; }
        [Column(TypeName = "text")]
        public string Reason { get; set; }
        public int? PaymentMethodId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DateIssued { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string AuthorizationState { get; set; }
        public int? Status { get; set; }

        [ForeignKey("DepartmentID")]
        [InverseProperty("TransactionTables")]
        public virtual Departments_Table Department { get; set; }
        [ForeignKey("PaymentMethodId")]
        [InverseProperty("TransactionTables")]
        public virtual PaymentMethodTable PaymentMethod { get; set; }
        [ForeignKey("ReviewerId")]
        [InverseProperty("TransactionTables")]
        public virtual ReviewersTable Reviewer { get; set; }
    }
}