// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NZUCManagementSystemIA.Shared.Models
{
    [Table("TransactionStatus")]
    public partial class TransactionStatus
    {
        public TransactionStatus()
        {
            ReviewTransactionTables = new HashSet<ReviewTransactionTable>();
        }

        [Key]
        public int ID { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string StatusType { get; set; }

        [InverseProperty("StatusNavigation")]
        public virtual ICollection<ReviewTransactionTable> ReviewTransactionTables { get; set; }
    }
}